// <auto-generated />
using System;
using GTERP.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GTERP.Migrations.gtrerp_all
{
    [DbContext(typeof(gtrerp_allContext))]
    partial class gtrerp_allContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AI")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GTERP.EF.HrProcessedDataSal", b =>
                {
                    b.Property<int?>("AEmpId")
                        .HasColumnType("int")
                        .HasColumnName("aEmpID");

                    b.Property<long>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("aId")
                        .UseIdentityColumn();

                    b.Property<decimal>("Ab")
                        .HasColumnType("money")
                        .HasColumnName("AB");

                    b.Property<short>("AbL")
                        .HasColumnType("smallint")
                        .HasColumnName("abL");

                    b.Property<decimal>("AbLamt")
                        .HasColumnType("money")
                        .HasColumnName("abLAmt");

                    b.Property<float>("Absent")
                        .HasColumnType("real");

                    b.Property<float>("AccL")
                        .HasColumnType("real");

                    b.Property<decimal>("AdjustedItded")
                        .HasColumnType("money")
                        .HasColumnName("AdjustedITDed");

                    b.Property<decimal>("Adv")
                        .HasColumnType("money")
                        .HasColumnName("ADV");

                    b.Property<decimal>("AdvAgainstExp")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvAgainstExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvExploanBal")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvFacility")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvInTaxDed")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvWagesDed")
                        .HasColumnType("money");

                    b.Property<int?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Arrear")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearBasic")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearBonus")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExp")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExp")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearHrexp")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExp");

                    b.Property<decimal>("ArrearHrexpBal")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpBal");

                    b.Property<decimal>("ArrearHrexpOther")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpOther");

                    b.Property<decimal>("ArrearHrexpOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpOtherBal");

                    b.Property<decimal>("ArrearInTaxDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearOt")
                        .HasColumnType("money")
                        .HasColumnName("ArrearOT");

                    b.Property<decimal>("AttAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("AttBonus")
                        .HasColumnType("money");

                    b.Property<string>("Band")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("BandSl")
                        .HasColumnType("int")
                        .HasColumnName("BandSL");

                    b.Property<int?>("Bank1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("BankAcNo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValueSql("('')");

                    b.Property<short>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("BankPay")
                        .HasColumnType("money");

                    b.Property<decimal>("BankPf")
                        .HasColumnType("money")
                        .HasColumnName("BankPF");

                    b.Property<float>("BasicRate")
                        .HasColumnType("real");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("Bcl")
                        .HasColumnType("money")
                        .HasColumnName("BCL");

                    b.Property<decimal>("Bel")
                        .HasColumnType("money")
                        .HasColumnName("BEL");

                    b.Property<decimal>("Bs")
                        .HasColumnType("money")
                        .HasColumnName("BS");

                    b.Property<decimal>("Bsded")
                        .HasColumnType("money")
                        .HasColumnName("BSDed");

                    b.Property<decimal>("Bsl")
                        .HasColumnType("money")
                        .HasColumnName("BSL");

                    b.Property<decimal>("CanteenAllow")
                        .HasColumnType("money");

                    b.Property<int?>("Cash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("CashPay")
                        .HasColumnType("money");

                    b.Property<decimal>("CashPf")
                        .HasColumnType("money")
                        .HasColumnName("CashPF");

                    b.Property<byte?>("Cf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CF")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("ChargeAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("CheForum")
                        .HasColumnType("money");

                    b.Property<decimal>("ChemicalAsso")
                        .HasColumnType("money");

                    b.Property<decimal>("ChemicalForum")
                        .HasColumnType("money");

                    b.Property<float>("Cl")
                        .HasColumnType("real")
                        .HasColumnName("CL");

                    b.Property<short?>("Clh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("CLH")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ComId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("ComPfCount")
                        .HasColumnType("money");

                    b.Property<decimal>("ComPfRefund")
                        .HasColumnType("money");

                    b.Property<decimal?>("Conf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("ContainSub")
                        .HasColumnType("money");

                    b.Property<decimal>("ConvAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("ConvAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ConveyanceAllow")
                        .HasColumnType("money");

                    b.Property<float>("CurrEl")
                        .HasColumnType("real")
                        .HasColumnName("CurrEL");

                    b.Property<decimal>("DapEmpClub")
                        .HasColumnType("money");

                    b.Property<decimal>("Dd")
                        .HasColumnType("money")
                        .HasColumnName("DD");

                    b.Property<float>("Dday")
                        .HasColumnType("real");

                    b.Property<decimal>("DearnessAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBns")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBnsBal")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBonusOf")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBonusOfBal")
                        .HasColumnType("money");

                    b.Property<short?>("DeptId")
                        .HasColumnType("smallint");

                    b.Property<short?>("DesigId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DiplomaassoDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Dishantenna")
                        .HasColumnType("money");

                    b.Property<decimal>("DishantennaRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Donation")
                        .HasColumnType("money");

                    b.Property<DateTime?>("DtInput")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtInput");

                    b.Property<DateTime?>("DtJoin")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtJoin");

                    b.Property<DateTime>("DtPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtPayment")
                        .HasDefaultValueSql("('00:00')");

                    b.Property<DateTime?>("DtPresentLast")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtPresentLast");

                    b.Property<string>("DtSalary")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("dtSalary");

                    b.Property<decimal>("EduAlloDed")
                        .HasColumnType("money");

                    b.Property<decimal>("EduAllow")
                        .HasColumnType("money");

                    b.Property<float>("El")
                        .HasColumnType("real")
                        .HasColumnName("EL");

                    b.Property<decimal>("Elamt")
                        .HasColumnType("money")
                        .HasColumnName("ELAmt");

                    b.Property<decimal>("ElectricCharge")
                        .HasColumnType("money");

                    b.Property<decimal>("ElectricChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ElectricityExpRefund")
                        .HasColumnType("money");

                    b.Property<float>("Elh")
                        .HasColumnType("real")
                        .HasColumnName("ELH");

                    b.Property<decimal>("EmpClubDed")
                        .HasColumnType("money");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmpID");

                    b.Property<string>("EmpSts")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("EmpTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EnggassoDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("Epf")
                        .HasColumnType("money")
                        .HasColumnName("epf");

                    b.Property<decimal>("ExOtamount")
                        .HasColumnType("money")
                        .HasColumnName("ExOTAmount");

                    b.Property<float>("ExOthr")
                        .HasColumnType("real")
                        .HasColumnName("ExOTHr");

                    b.Property<float>("ExOtmin")
                        .HasColumnType("real")
                        .HasColumnName("ExOTMin");

                    b.Property<decimal>("ExchRate")
                        .HasColumnType("smallmoney");

                    b.Property<decimal>("Fbonus")
                        .HasColumnType("money")
                        .HasColumnName("FBonus");

                    b.Property<float>("Fcttl")
                        .HasColumnType("real")
                        .HasColumnName("FCTtl");

                    b.Property<decimal>("FesBonusDed")
                        .HasColumnType("money");

                    b.Property<decimal>("FesBonusDedBal")
                        .HasColumnType("money");

                    b.Property<decimal>("FestivalBonus")
                        .HasColumnType("money");

                    b.Property<int>("FiscalMonthId")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("FoodAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("GasAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("GasChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("GasExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Gascharge")
                        .HasColumnType("money");

                    b.Property<int>("Glid")
                        .HasColumnType("int")
                        .HasColumnName("GLId");

                    b.Property<decimal>("Gp")
                        .HasColumnType("money")
                        .HasColumnName("GP");

                    b.Property<string>("Grade")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("GradeAmt")
                        .HasColumnType("money");

                    b.Property<string>("GradeSal")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("GrossBank")
                        .HasColumnType("money");

                    b.Property<decimal>("GrossCash")
                        .HasColumnType("money");

                    b.Property<decimal>("Gs")
                        .HasColumnType("money")
                        .HasColumnName("GS");

                    b.Property<decimal?>("Gsdiff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallmoney")
                        .HasColumnName("GSDiff")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Gsfinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("GSFinal")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Gsmin")
                        .HasColumnType("smallmoney")
                        .HasColumnName("GSMin");

                    b.Property<decimal>("Gsusd")
                        .HasColumnType("money")
                        .HasColumnName("GSUSD");

                    b.Property<decimal>("HazScheme")
                        .HasColumnType("money");

                    b.Property<int>("Hblid")
                        .HasColumnType("int")
                        .HasColumnName("HBLId");

                    b.Property<int>("Hblid2")
                        .HasColumnType("int")
                        .HasColumnName("HBLId2");

                    b.Property<int>("Hblid3")
                        .HasColumnType("int")
                        .HasColumnName("HBLId3");

                    b.Property<decimal>("HbloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("HBLoanBalance");

                    b.Property<decimal>("HbloanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther1")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther2")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal1")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal2")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanRefund")
                        .HasColumnType("money")
                        .HasColumnName("HBLoanRefund");

                    b.Property<float>("Hday")
                        .HasColumnType("real");

                    b.Property<decimal>("HdayBonus")
                        .HasColumnType("money")
                        .HasColumnName("HDayBonus");

                    b.Property<float>("HdayP")
                        .HasColumnType("real")
                        .HasColumnName("HDayP");

                    b.Property<decimal>("HouseRent")
                        .HasColumnType("money");

                    b.Property<decimal>("Hr")
                        .HasColumnType("money")
                        .HasColumnName("HR");

                    b.Property<decimal>("HrExp")
                        .HasColumnType("money");

                    b.Property<decimal>("Hrded")
                        .HasColumnType("money")
                        .HasColumnName("HRDed");

                    b.Property<decimal>("HrexpOther")
                        .HasColumnType("money")
                        .HasColumnName("HRExpOther");

                    b.Property<decimal>("HrexpRefund")
                        .HasColumnType("money")
                        .HasColumnName("HRExpRefund");

                    b.Property<decimal?>("Inc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("IncBonusDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("IncenBns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("money");

                    b.Property<decimal>("IncomeTaxRefund")
                        .HasColumnType("money");

                    b.Property<byte?>("IsAllowGradeBns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte>("IsAllowOt")
                        .HasColumnType("tinyint")
                        .HasColumnName("IsAllowOT");

                    b.Property<byte>("IsAllowPf")
                        .HasColumnType("tinyint")
                        .HasColumnName("IsAllowPF");

                    b.Property<byte?>("IsManual")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsNewJoin")
                        .HasColumnType("tinyint")
                        .HasColumnName("isNewJoin");

                    b.Property<bool>("IsOk")
                        .HasColumnType("bit")
                        .HasColumnName("IsOK");

                    b.Property<byte?>("IsReleased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((0))")
                        .HasComment("for past historical Data");

                    b.Property<float>("Late")
                        .HasColumnType("real");

                    b.Property<float>("LateHr")
                        .HasColumnType("real");

                    b.Property<float>("LateMin")
                        .HasColumnType("real");

                    b.Property<int>("Lid1")
                        .HasColumnType("int")
                        .HasColumnName("LId1");

                    b.Property<int>("Lid2")
                        .HasColumnType("int")
                        .HasColumnName("LId2");

                    b.Property<int>("Lid3")
                        .HasColumnType("int")
                        .HasColumnName("LId3");

                    b.Property<string>("Line")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("LineSl")
                        .HasColumnType("int")
                        .HasColumnName("LineSL");

                    b.Property<decimal?>("Loan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("LoanBalance")
                        .HasColumnType("money");

                    b.Property<short?>("Lunch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<short?>("LunchAmt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<short?>("Lwp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("LWP")
                        .HasDefaultValueSql("((0))");

                    b.Property<short?>("Lwppay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("LWPPay")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Ma")
                        .HasColumnType("money")
                        .HasColumnName("MA");

                    b.Property<decimal>("Maded")
                        .HasColumnType("money")
                        .HasColumnName("MADed");

                    b.Property<decimal>("MadicalAllow")
                        .HasColumnType("money");

                    b.Property<float>("ManualDay")
                        .HasColumnType("real");

                    b.Property<decimal>("MaterialLoanDed")
                        .HasColumnType("money");

                    b.Property<int>("Mclid")
                        .HasColumnType("int")
                        .HasColumnName("MCLId");

                    b.Property<decimal>("McloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("MCLoanBalance");

                    b.Property<decimal>("McloanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("McloanDedOther")
                        .HasColumnType("money");

                    b.Property<decimal>("McloanDedOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("MCloanDedOtherBal");

                    b.Property<decimal>("MedicalExp")
                        .HasColumnType("money");

                    b.Property<decimal>("MedicalLoanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("MiscAddAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("MiscDed")
                        .HasColumnType("money");

                    b.Property<float>("Ml")
                        .HasColumnType("real")
                        .HasColumnName("ML");

                    b.Property<decimal?>("Mlpay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("MLPay")
                        .HasDefaultValueSql("((0))");

                    b.Property<byte>("MngType")
                        .HasColumnType("tinyint");

                    b.Property<short?>("MobileAllow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<short?>("MobileDeduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Moktab")
                        .HasColumnType("money");

                    b.Property<string>("Month")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("NetFoodAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("NetOtamt")
                        .HasColumnType("money")
                        .HasColumnName("NetOTAmt");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("NetSalaryB")
                        .HasColumnType("money");

                    b.Property<decimal?>("NetSalaryBuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("NetSalaryPayable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("NetSalaryPayableB")
                        .HasColumnType("money");

                    b.Property<short?>("Night")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("NightAllow")
                        .HasColumnType("money");

                    b.Property<short?>("NightAmt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("NoticePayDed")
                        .HasColumnType("money");

                    b.Property<decimal>("OffDayAllowAmt")
                        .HasColumnType("money");

                    b.Property<decimal>("OffWlfareAsso")
                        .HasColumnType("money");

                    b.Property<decimal>("OfficeclubDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Ot")
                        .HasColumnType("money")
                        .HasColumnName("OT");

                    b.Property<decimal>("OtallowAmt")
                        .HasColumnType("money")
                        .HasColumnName("OTAllowAmt");

                    b.Property<decimal?>("OtamtBuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("OTAmtBuyer")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Otdes")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OTDes");

                    b.Property<string>("OtherAddType")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("OtherAllow")
                        .HasColumnType("money");

                    b.Property<string>("OtherDedType")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("OtherLoanBalance")
                        .HasColumnType("money");

                    b.Property<decimal>("OtherloannDed")
                        .HasColumnType("money");

                    b.Property<decimal>("OthersAddition")
                        .HasColumnType("money");

                    b.Property<decimal>("OthersDeduct")
                        .HasColumnType("money");

                    b.Property<float>("OthrTtl")
                        .HasColumnType("real")
                        .HasColumnName("OTHrTtl");

                    b.Property<float?>("Othrbuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasColumnName("OTHRBuyer")
                        .HasDefaultValueSql("((0))");

                    b.Property<float>("OtminTtl")
                        .HasColumnType("real")
                        .HasColumnName("OTMinTtl");

                    b.Property<decimal>("Otrate")
                        .HasColumnType("money")
                        .HasColumnName("OTRate");

                    b.Property<decimal>("Otstamp")
                        .HasColumnType("money")
                        .HasColumnName("OTStamp");

                    b.Property<decimal>("OwaSub")
                        .HasColumnType("money");

                    b.Property<string>("PayMode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaySlipNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaySource")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Pbonus")
                        .HasColumnType("money")
                        .HasColumnName("PBonus");

                    b.Property<float>("Pday")
                        .HasColumnType("real")
                        .HasComment("Day of Payment");

                    b.Property<decimal>("PersonalPay")
                        .HasColumnType("money");

                    b.Property<decimal>("Pf")
                        .HasColumnType("money")
                        .HasColumnName("PF");

                    b.Property<decimal>("PfAdd")
                        .HasColumnType("money");

                    b.Property<decimal>("Pfcom")
                        .HasColumnType("money")
                        .HasColumnName("PFCom");

                    b.Property<int>("Pflid")
                        .HasColumnType("int")
                        .HasColumnName("PFLId");

                    b.Property<int>("Pfllid")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId");

                    b.Property<int>("Pfllid2")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId2");

                    b.Property<int>("Pfllid3")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId3");

                    b.Property<decimal>("PfloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("PFLoanBalance");

                    b.Property<decimal>("PfloanDedOther")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther");

                    b.Property<decimal>("PfloanDedOther1")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther1");

                    b.Property<decimal>("PfloanDedOther2")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther2");

                    b.Property<decimal>("PfloanDedOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal");

                    b.Property<decimal>("PfloanDedOtherBal1")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal1");

                    b.Property<decimal>("PfloanDedOtherBal2")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal2");

                    b.Property<decimal>("PfloanRefund")
                        .HasColumnType("money")
                        .HasColumnName("PFLoanRefund");

                    b.Property<decimal>("PfloannDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Pfown")
                        .HasColumnType("money")
                        .HasColumnName("PFOwn");

                    b.Property<decimal>("Pfprofit")
                        .HasColumnType("money")
                        .HasColumnName("PFProfit");

                    b.Property<decimal>("Pp")
                        .HasColumnType("money")
                        .HasColumnName("PP");

                    b.Property<short>("PreLeave")
                        .HasColumnType("smallint");

                    b.Property<float>("Present")
                        .HasColumnType("real");

                    b.Property<float>("PrevEl")
                        .HasColumnType("real")
                        .HasColumnName("PrevEL");

                    b.Property<short>("ProLeave")
                        .HasColumnType("smallint");

                    b.Property<string>("ProssType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PurChange")
                        .HasColumnType("money");

                    b.Property<decimal>("PurchaseAdv")
                        .HasColumnType("money");

                    b.Property<string>("Remarks")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("RevenueStamp")
                        .HasColumnType("money");

                    b.Property<decimal>("RiskAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("RiskDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("Rvi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("RVI")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("SalAdvBal")
                        .HasColumnType("money");

                    b.Property<decimal>("SalaryAdv")
                        .HasColumnType("money");

                    b.Property<short>("SectId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ServiceBenefit")
                        .HasColumnType("money");

                    b.Property<float>("ServiceMonth")
                        .HasColumnType("real");

                    b.Property<float>("ServiceYear")
                        .HasColumnType("real");

                    b.Property<decimal>("ShiftAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftAllowDedBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftAllowanceAmt")
                        .HasColumnType("smallmoney");

                    b.Property<decimal>("ShiftAmt")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftIncenAmt")
                        .HasColumnType("smallmoney");

                    b.Property<float>("ShiftTtl")
                        .HasColumnType("real");

                    b.Property<decimal>("SiftAllow")
                        .HasColumnType("money");

                    b.Property<float>("Sl")
                        .HasColumnType("real")
                        .HasColumnName("SL");

                    b.Property<short?>("Slh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("SLH")
                        .HasDefaultValueSql("((0))");

                    b.Property<float>("Spl")
                        .HasColumnType("real")
                        .HasColumnName("SPL");

                    b.Property<decimal>("Stamp")
                        .HasColumnType("smallmoney");

                    b.Property<short?>("SubSectId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Taexpense")
                        .HasColumnType("money")
                        .HasColumnName("TAExpense");

                    b.Property<decimal>("TeliphoneCharge")
                        .HasColumnType("money");

                    b.Property<decimal>("TiffinAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("TiffinAllowDed")
                        .HasColumnType("money");

                    b.Property<int>("Tk1")
                        .HasColumnType("int")
                        .HasColumnName("TK1");

                    b.Property<int>("Tk10")
                        .HasColumnType("int")
                        .HasColumnName("TK10");

                    b.Property<int>("Tk100")
                        .HasColumnType("int")
                        .HasColumnName("TK100");

                    b.Property<int>("Tk1000")
                        .HasColumnType("int")
                        .HasColumnName("TK1000");

                    b.Property<int>("Tk2")
                        .HasColumnType("int")
                        .HasColumnName("TK2");

                    b.Property<int>("Tk20")
                        .HasColumnType("int")
                        .HasColumnName("TK20");

                    b.Property<int>("Tk5")
                        .HasColumnType("int")
                        .HasColumnName("TK5");

                    b.Property<int>("Tk50")
                        .HasColumnType("int")
                        .HasColumnName("TK50");

                    b.Property<int>("Tk500")
                        .HasColumnType("int")
                        .HasColumnName("TK500");

                    b.Property<decimal>("TotalAddition")
                        .HasColumnType("money");

                    b.Property<decimal?>("TotalDeduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("TotalDeductBank")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDeductCash")
                        .HasColumnType("money");

                    b.Property<float>("TotalOffDay")
                        .HasColumnType("real");

                    b.Property<string>("TotalOt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TotalOT");

                    b.Property<string>("TotalOtb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TotalOTB");

                    b.Property<decimal?>("TotalPayable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("money");

                    b.Property<float>("TotalWorkDay")
                        .HasColumnType("real");

                    b.Property<decimal>("TotaldeductB")
                        .HasColumnType("money")
                        .HasColumnName("totaldeductB");

                    b.Property<decimal>("TotalpayableB")
                        .HasColumnType("money")
                        .HasColumnName("totalpayableB");

                    b.Property<decimal>("Transportcharge")
                        .HasColumnType("money");

                    b.Property<decimal>("Trn")
                        .HasColumnType("money");

                    b.Property<double?>("Trnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("trnd")
                        .HasDefaultValueSql("((0))");

                    b.Property<short?>("TtlAbsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("UniFormAdd")
                        .HasColumnType("money");

                    b.Property<decimal>("UniFormDed")
                        .HasColumnType("money");

                    b.Property<decimal>("UnionSubDed")
                        .HasColumnType("money");

                    b.Property<string>("UnitName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("VigilanceDutyAllow")
                        .HasColumnType("money");

                    b.Property<Guid>("WId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wId")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("WagesaAdv")
                        .HasColumnType("money");

                    b.Property<decimal>("WagesaAdvBal")
                        .HasColumnType("money");

                    b.Property<decimal>("WashingAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("WashingAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("WaterChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("WaterExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Watercharge")
                        .HasColumnType("money");

                    b.Property<float>("Wday")
                        .HasColumnType("real");

                    b.Property<float>("WdayP")
                        .HasColumnType("real")
                        .HasColumnName("WDayP");

                    b.Property<int>("WelfareLid")
                        .HasColumnType("int")
                        .HasColumnName("WelfareLId");

                    b.Property<decimal>("Wfl")
                        .HasColumnType("money")
                        .HasColumnName("WFL");

                    b.Property<decimal>("WflloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("WFLLoanBalance");

                    b.Property<decimal>("WfloanLocal")
                        .HasColumnType("money");

                    b.Property<decimal>("WfloanOther")
                        .HasColumnType("money");

                    b.Property<decimal>("WfloanOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("Wfsub")
                        .HasColumnType("money");

                    b.Property<float>("WhdayAbsent")
                        .HasColumnType("real")
                        .HasColumnName("WHDayAbsent");

                    b.Property<decimal>("WhdayOtamt")
                        .HasColumnType("smallmoney")
                        .HasColumnName("WHDayOTAmt");

                    b.Property<float>("WhdayOthr")
                        .HasColumnType("real")
                        .HasColumnName("WHDayOTHr");

                    b.Property<float>("WhdayP")
                        .HasColumnType("real")
                        .HasColumnName("WHDayP");

                    b.Property<float>("WorkingDays")
                        .HasColumnType("real");

                    b.Property<decimal>("WpfloanDed")
                        .HasColumnType("money");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.ToTable("HR_ProcessedDataSal");
                });

            modelBuilder.Entity("GTERP.EF.HrProcessedDataSalUpdate", b =>
                {
                    b.Property<int>("Suid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("suid")
                        .UseIdentityColumn();

                    b.Property<int?>("AEmpId")
                        .HasColumnType("int")
                        .HasColumnName("aEmpID");

                    b.Property<long>("AId")
                        .HasColumnType("bigint")
                        .HasColumnName("aId");

                    b.Property<decimal>("Ab")
                        .HasColumnType("money")
                        .HasColumnName("AB");

                    b.Property<short>("AbL")
                        .HasColumnType("smallint")
                        .HasColumnName("abL");

                    b.Property<decimal>("AbLamt")
                        .HasColumnType("money")
                        .HasColumnName("abLAmt");

                    b.Property<float>("Absent")
                        .HasColumnType("real");

                    b.Property<float>("AccL")
                        .HasColumnType("real");

                    b.Property<decimal>("AdjustedItded")
                        .HasColumnType("money")
                        .HasColumnName("AdjustedITDed");

                    b.Property<decimal>("Adv")
                        .HasColumnType("money")
                        .HasColumnName("ADV");

                    b.Property<decimal>("AdvAgainstExp")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvAgainstExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvExploanBal")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvFacility")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvInTaxDed")
                        .HasColumnType("money");

                    b.Property<decimal>("AdvWagesDed")
                        .HasColumnType("money");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<decimal>("Arrear")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearBasic")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearBonus")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExp")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearElectricityExpOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExp")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearGasExpOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearHrexp")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExp");

                    b.Property<decimal>("ArrearHrexpBal")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpBal");

                    b.Property<decimal>("ArrearHrexpOther")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpOther");

                    b.Property<decimal>("ArrearHrexpOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("ArrearHRExpOtherBal");

                    b.Property<decimal>("ArrearInTaxDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ArrearOt")
                        .HasColumnType("money")
                        .HasColumnName("ArrearOT");

                    b.Property<decimal>("AttAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("AttBonus")
                        .HasColumnType("money");

                    b.Property<string>("Band")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("BandSl")
                        .HasColumnType("int")
                        .HasColumnName("BandSL");

                    b.Property<int?>("Bank1")
                        .HasColumnType("int");

                    b.Property<string>("BankAcNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<short>("BankId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("BankPay")
                        .HasColumnType("money");

                    b.Property<decimal>("BankPf")
                        .HasColumnType("money")
                        .HasColumnName("BankPF");

                    b.Property<float>("BasicRate")
                        .HasColumnType("real");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("Bcl")
                        .HasColumnType("money")
                        .HasColumnName("BCL");

                    b.Property<decimal>("Bel")
                        .HasColumnType("money")
                        .HasColumnName("BEL");

                    b.Property<decimal>("Bs")
                        .HasColumnType("money")
                        .HasColumnName("BS");

                    b.Property<decimal>("Bsded")
                        .HasColumnType("money")
                        .HasColumnName("BSDed");

                    b.Property<decimal>("Bsl")
                        .HasColumnType("money")
                        .HasColumnName("BSL");

                    b.Property<decimal>("CanteenAllow")
                        .HasColumnType("money");

                    b.Property<int?>("Cash")
                        .HasColumnType("int");

                    b.Property<decimal>("CashPay")
                        .HasColumnType("money");

                    b.Property<decimal>("CashPf")
                        .HasColumnType("money")
                        .HasColumnName("CashPF");

                    b.Property<byte?>("Cf")
                        .HasColumnType("tinyint")
                        .HasColumnName("CF");

                    b.Property<decimal>("ChargeAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("CheForum")
                        .HasColumnType("money");

                    b.Property<decimal>("ChemicalAsso")
                        .HasColumnType("money");

                    b.Property<decimal>("ChemicalForum")
                        .HasColumnType("money");

                    b.Property<float>("Cl")
                        .HasColumnType("real")
                        .HasColumnName("CL");

                    b.Property<short?>("Clh")
                        .HasColumnType("smallint")
                        .HasColumnName("CLH");

                    b.Property<string>("ComId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("ComPfCount")
                        .HasColumnType("money");

                    b.Property<decimal>("ComPfRefund")
                        .HasColumnType("money");

                    b.Property<decimal?>("Conf")
                        .HasColumnType("money");

                    b.Property<decimal>("ContainSub")
                        .HasColumnType("money");

                    b.Property<decimal>("ConvAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("ConvAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ConveyanceAllow")
                        .HasColumnType("money");

                    b.Property<float>("CurrEl")
                        .HasColumnType("real")
                        .HasColumnName("CurrEL");

                    b.Property<decimal>("DapEmpClub")
                        .HasColumnType("money");

                    b.Property<decimal>("Dd")
                        .HasColumnType("money")
                        .HasColumnName("DD");

                    b.Property<float>("Dday")
                        .HasColumnType("real");

                    b.Property<decimal>("DearnessAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBns")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBnsBal")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBonusOf")
                        .HasColumnType("money");

                    b.Property<decimal>("DedIncBonusOfBal")
                        .HasColumnType("money");

                    b.Property<short?>("DeptId")
                        .HasColumnType("smallint");

                    b.Property<short?>("DesigId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DiplomaassoDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Dishantenna")
                        .HasColumnType("money");

                    b.Property<decimal>("DishantennaRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Donation")
                        .HasColumnType("money");

                    b.Property<DateTime?>("DtInput")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtInput");

                    b.Property<DateTime?>("DtJoin")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtJoin");

                    b.Property<DateTime>("DtPayment")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtPayment");

                    b.Property<DateTime?>("DtPresentLast")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("dtPresentLast");

                    b.Property<string>("DtSalary")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("dtSalary");

                    b.Property<decimal>("EduAlloDed")
                        .HasColumnType("money");

                    b.Property<decimal>("EduAllow")
                        .HasColumnType("money");

                    b.Property<float>("El")
                        .HasColumnType("real")
                        .HasColumnName("EL");

                    b.Property<decimal>("Elamt")
                        .HasColumnType("money")
                        .HasColumnName("ELAmt");

                    b.Property<decimal>("ElectricCharge")
                        .HasColumnType("money");

                    b.Property<decimal>("ElectricChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("ElectricityExpRefund")
                        .HasColumnType("money");

                    b.Property<float>("Elh")
                        .HasColumnType("real")
                        .HasColumnName("ELH");

                    b.Property<decimal>("EmpClubDed")
                        .HasColumnType("money");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmpID");

                    b.Property<string>("EmpSts")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("EmpTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EnggassoDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("Epf")
                        .HasColumnType("money")
                        .HasColumnName("epf");

                    b.Property<decimal>("ExOtamount")
                        .HasColumnType("money")
                        .HasColumnName("ExOTAmount");

                    b.Property<float>("ExOthr")
                        .HasColumnType("real")
                        .HasColumnName("ExOTHr");

                    b.Property<float>("ExOtmin")
                        .HasColumnType("real")
                        .HasColumnName("ExOTMin");

                    b.Property<decimal>("ExchRate")
                        .HasColumnType("smallmoney");

                    b.Property<decimal>("Fbonus")
                        .HasColumnType("money")
                        .HasColumnName("FBonus");

                    b.Property<float>("Fcttl")
                        .HasColumnType("real")
                        .HasColumnName("FCTtl");

                    b.Property<decimal>("FesBonusDed")
                        .HasColumnType("money");

                    b.Property<decimal>("FesBonusDedBal")
                        .HasColumnType("money");

                    b.Property<decimal>("FestivalBonus")
                        .HasColumnType("money");

                    b.Property<int>("FiscalMonthId")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("FoodAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("GasAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("GasChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("GasExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Gascharge")
                        .HasColumnType("money");

                    b.Property<int>("Glid")
                        .HasColumnType("int")
                        .HasColumnName("GLId");

                    b.Property<decimal>("Gp")
                        .HasColumnType("money")
                        .HasColumnName("GP");

                    b.Property<string>("Grade")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("GradeAmt")
                        .HasColumnType("money");

                    b.Property<string>("GradeSal")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("GrossBank")
                        .HasColumnType("money");

                    b.Property<decimal>("GrossCash")
                        .HasColumnType("money");

                    b.Property<decimal>("Gs")
                        .HasColumnType("money")
                        .HasColumnName("GS");

                    b.Property<decimal?>("Gsdiff")
                        .HasColumnType("smallmoney")
                        .HasColumnName("GSDiff");

                    b.Property<decimal?>("Gsfinal")
                        .HasColumnType("money")
                        .HasColumnName("GSFinal");

                    b.Property<decimal?>("Gsmin")
                        .HasColumnType("smallmoney")
                        .HasColumnName("GSMin");

                    b.Property<decimal>("Gsusd")
                        .HasColumnType("money")
                        .HasColumnName("GSUSD");

                    b.Property<decimal>("HazScheme")
                        .HasColumnType("money");

                    b.Property<int>("Hblid")
                        .HasColumnType("int")
                        .HasColumnName("HBLId");

                    b.Property<int>("Hblid2")
                        .HasColumnType("int")
                        .HasColumnName("HBLId2");

                    b.Property<int>("Hblid3")
                        .HasColumnType("int")
                        .HasColumnName("HBLId3");

                    b.Property<decimal>("HbloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("HBLoanBalance");

                    b.Property<decimal>("HbloanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther1")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOther2")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal1")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanDedOtherBal2")
                        .HasColumnType("money");

                    b.Property<decimal>("HbloanRefund")
                        .HasColumnType("money")
                        .HasColumnName("HBLoanRefund");

                    b.Property<float>("Hday")
                        .HasColumnType("real");

                    b.Property<decimal>("HdayBonus")
                        .HasColumnType("money")
                        .HasColumnName("HDayBonus");

                    b.Property<float>("HdayP")
                        .HasColumnType("real")
                        .HasColumnName("HDayP");

                    b.Property<decimal>("HouseRent")
                        .HasColumnType("money");

                    b.Property<decimal>("Hr")
                        .HasColumnType("money")
                        .HasColumnName("HR");

                    b.Property<decimal>("HrExp")
                        .HasColumnType("money");

                    b.Property<decimal>("Hrded")
                        .HasColumnType("money")
                        .HasColumnName("HRDed");

                    b.Property<decimal>("HrexpOther")
                        .HasColumnType("money")
                        .HasColumnName("HRExpOther");

                    b.Property<decimal>("HrexpRefund")
                        .HasColumnType("money")
                        .HasColumnName("HRExpRefund");

                    b.Property<decimal?>("Inc")
                        .HasColumnType("money");

                    b.Property<decimal>("IncBonusDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("IncenBns")
                        .HasColumnType("money");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("money");

                    b.Property<decimal>("IncomeTaxRefund")
                        .HasColumnType("money");

                    b.Property<byte?>("IsAllowGradeBns")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsAllowOt")
                        .HasColumnType("tinyint")
                        .HasColumnName("IsAllowOT");

                    b.Property<byte>("IsAllowPf")
                        .HasColumnType("tinyint")
                        .HasColumnName("IsAllowPF");

                    b.Property<byte?>("IsManual")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsNewJoin")
                        .HasColumnType("tinyint")
                        .HasColumnName("isNewJoin");

                    b.Property<bool>("IsOk")
                        .HasColumnType("bit")
                        .HasColumnName("IsOK");

                    b.Property<byte?>("IsReleased")
                        .HasColumnType("tinyint");

                    b.Property<float>("Late")
                        .HasColumnType("real");

                    b.Property<float>("LateHr")
                        .HasColumnType("real");

                    b.Property<float>("LateMin")
                        .HasColumnType("real");

                    b.Property<int>("Lid1")
                        .HasColumnType("int")
                        .HasColumnName("LId1");

                    b.Property<int>("Lid2")
                        .HasColumnType("int")
                        .HasColumnName("LId2");

                    b.Property<int>("Lid3")
                        .HasColumnType("int")
                        .HasColumnName("LId3");

                    b.Property<string>("Line")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("LineSl")
                        .HasColumnType("int")
                        .HasColumnName("LineSL");

                    b.Property<decimal?>("Loan")
                        .HasColumnType("money");

                    b.Property<decimal>("LoanBalance")
                        .HasColumnType("money");

                    b.Property<short?>("Lunch")
                        .HasColumnType("smallint");

                    b.Property<short?>("LunchAmt")
                        .HasColumnType("smallint");

                    b.Property<short?>("Lwp")
                        .HasColumnType("smallint")
                        .HasColumnName("LWP");

                    b.Property<short?>("Lwppay")
                        .HasColumnType("smallint")
                        .HasColumnName("LWPPay");

                    b.Property<decimal>("Ma")
                        .HasColumnType("money")
                        .HasColumnName("MA");

                    b.Property<decimal>("Maded")
                        .HasColumnType("money")
                        .HasColumnName("MADed");

                    b.Property<decimal>("MadicalAllow")
                        .HasColumnType("money");

                    b.Property<float>("ManualDay")
                        .HasColumnType("real");

                    b.Property<decimal>("MaterialLoanDed")
                        .HasColumnType("money");

                    b.Property<int>("Mclid")
                        .HasColumnType("int")
                        .HasColumnName("MCLId");

                    b.Property<decimal>("McloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("MCLoanBalance");

                    b.Property<decimal>("McloanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("McloanDedOther")
                        .HasColumnType("money");

                    b.Property<decimal>("McloanDedOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("MCloanDedOtherBal");

                    b.Property<decimal>("MedicalExp")
                        .HasColumnType("money");

                    b.Property<decimal>("MedicalLoanDed")
                        .HasColumnType("money");

                    b.Property<decimal>("MiscAddAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("MiscDed")
                        .HasColumnType("money");

                    b.Property<float>("Ml")
                        .HasColumnType("real")
                        .HasColumnName("ML");

                    b.Property<decimal?>("Mlpay")
                        .HasColumnType("money")
                        .HasColumnName("MLPay");

                    b.Property<byte>("MngType")
                        .HasColumnType("tinyint");

                    b.Property<short?>("MobileAllow")
                        .HasColumnType("smallint");

                    b.Property<short?>("MobileDeduction")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Moktab")
                        .HasColumnType("money");

                    b.Property<string>("Month")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("NetFoodAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("NetOtamt")
                        .HasColumnType("money")
                        .HasColumnName("NetOTAmt");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("NetSalaryB")
                        .HasColumnType("money");

                    b.Property<decimal?>("NetSalaryBuyer")
                        .HasColumnType("money");

                    b.Property<decimal?>("NetSalaryPayable")
                        .HasColumnType("money");

                    b.Property<decimal>("NetSalaryPayableB")
                        .HasColumnType("money");

                    b.Property<short?>("Night")
                        .HasColumnType("smallint");

                    b.Property<decimal>("NightAllow")
                        .HasColumnType("money");

                    b.Property<short?>("NightAmt")
                        .HasColumnType("smallint");

                    b.Property<decimal>("NoticePayDed")
                        .HasColumnType("money");

                    b.Property<decimal>("OffDayAllowAmt")
                        .HasColumnType("money");

                    b.Property<decimal>("OffWlfareAsso")
                        .HasColumnType("money");

                    b.Property<decimal>("OfficeclubDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Ot")
                        .HasColumnType("money")
                        .HasColumnName("OT");

                    b.Property<decimal>("OtallowAmt")
                        .HasColumnType("money")
                        .HasColumnName("OTAllowAmt");

                    b.Property<decimal?>("OtamtBuyer")
                        .HasColumnType("money")
                        .HasColumnName("OTAmtBuyer");

                    b.Property<string>("Otdes")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OTDes");

                    b.Property<string>("OtherAddType")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("OtherAllow")
                        .HasColumnType("money");

                    b.Property<string>("OtherDedType")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("OtherLoanBalance")
                        .HasColumnType("money");

                    b.Property<decimal>("OtherloannDed")
                        .HasColumnType("money");

                    b.Property<decimal>("OthersAddition")
                        .HasColumnType("money");

                    b.Property<decimal>("OthersDeduct")
                        .HasColumnType("money");

                    b.Property<float>("OthrTtl")
                        .HasColumnType("real")
                        .HasColumnName("OTHrTtl");

                    b.Property<float?>("Othrbuyer")
                        .HasColumnType("real")
                        .HasColumnName("OTHRBuyer");

                    b.Property<float>("OtminTtl")
                        .HasColumnType("real")
                        .HasColumnName("OTMinTtl");

                    b.Property<decimal>("Otrate")
                        .HasColumnType("money")
                        .HasColumnName("OTRate");

                    b.Property<decimal>("Otstamp")
                        .HasColumnType("money")
                        .HasColumnName("OTStamp");

                    b.Property<decimal>("OwaSub")
                        .HasColumnType("money");

                    b.Property<string>("PayMode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaySlipNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaySource")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Pbonus")
                        .HasColumnType("money")
                        .HasColumnName("PBonus");

                    b.Property<float>("Pday")
                        .HasColumnType("real");

                    b.Property<decimal>("PersonalPay")
                        .HasColumnType("money");

                    b.Property<decimal>("Pf")
                        .HasColumnType("money")
                        .HasColumnName("PF");

                    b.Property<decimal>("PfAdd")
                        .HasColumnType("money");

                    b.Property<decimal>("Pfcom")
                        .HasColumnType("money")
                        .HasColumnName("PFCom");

                    b.Property<int>("Pflid")
                        .HasColumnType("int")
                        .HasColumnName("PFLId");

                    b.Property<int>("Pfllid")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId");

                    b.Property<int>("Pfllid2")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId2");

                    b.Property<int>("Pfllid3")
                        .HasColumnType("int")
                        .HasColumnName("PFLLId3");

                    b.Property<decimal>("PfloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("PFLoanBalance");

                    b.Property<decimal>("PfloanDedOther")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther");

                    b.Property<decimal>("PfloanDedOther1")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther1");

                    b.Property<decimal>("PfloanDedOther2")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOther2");

                    b.Property<decimal>("PfloanDedOtherBal")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal");

                    b.Property<decimal>("PfloanDedOtherBal1")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal1");

                    b.Property<decimal>("PfloanDedOtherBal2")
                        .HasColumnType("money")
                        .HasColumnName("PFloanDedOtherBal2");

                    b.Property<decimal>("PfloanRefund")
                        .HasColumnType("money")
                        .HasColumnName("PFLoanRefund");

                    b.Property<decimal>("PfloannDed")
                        .HasColumnType("money");

                    b.Property<decimal>("Pfown")
                        .HasColumnType("money")
                        .HasColumnName("PFOwn");

                    b.Property<decimal>("Pfprofit")
                        .HasColumnType("money")
                        .HasColumnName("PFProfit");

                    b.Property<decimal>("Pp")
                        .HasColumnType("money")
                        .HasColumnName("PP");

                    b.Property<short>("PreLeave")
                        .HasColumnType("smallint");

                    b.Property<float>("Present")
                        .HasColumnType("real");

                    b.Property<float>("PrevEl")
                        .HasColumnType("real")
                        .HasColumnName("PrevEL");

                    b.Property<short>("ProLeave")
                        .HasColumnType("smallint");

                    b.Property<string>("ProssType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PurChange")
                        .HasColumnType("money");

                    b.Property<decimal>("PurchaseAdv")
                        .HasColumnType("money");

                    b.Property<string>("Remarks")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("RevenueStamp")
                        .HasColumnType("money");

                    b.Property<decimal>("RiskAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("RiskDed")
                        .HasColumnType("money");

                    b.Property<decimal?>("Rvi")
                        .HasColumnType("money")
                        .HasColumnName("RVI");

                    b.Property<decimal>("SalAdvBal")
                        .HasColumnType("money");

                    b.Property<decimal>("SalaryAdv")
                        .HasColumnType("money");

                    b.Property<short>("SectId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ServiceBenefit")
                        .HasColumnType("money");

                    b.Property<float>("ServiceMonth")
                        .HasColumnType("real");

                    b.Property<float>("ServiceYear")
                        .HasColumnType("real");

                    b.Property<decimal>("ShiftAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftAllowDedBal")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftAllowanceAmt")
                        .HasColumnType("smallmoney");

                    b.Property<decimal>("ShiftAmt")
                        .HasColumnType("money");

                    b.Property<decimal>("ShiftIncenAmt")
                        .HasColumnType("smallmoney");

                    b.Property<float>("ShiftTtl")
                        .HasColumnType("real");

                    b.Property<decimal>("SiftAllow")
                        .HasColumnType("money");

                    b.Property<float>("Sl")
                        .HasColumnType("real")
                        .HasColumnName("SL");

                    b.Property<short?>("Slh")
                        .HasColumnType("smallint")
                        .HasColumnName("SLH");

                    b.Property<float>("Spl")
                        .HasColumnType("real")
                        .HasColumnName("SPL");

                    b.Property<decimal>("Stamp")
                        .HasColumnType("smallmoney");

                    b.Property<short?>("SubSectId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Taexpense")
                        .HasColumnType("money")
                        .HasColumnName("TAExpense");

                    b.Property<decimal>("TeliphoneCharge")
                        .HasColumnType("money");

                    b.Property<decimal>("TiffinAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("TiffinAllowDed")
                        .HasColumnType("money");

                    b.Property<int>("Tk1")
                        .HasColumnType("int")
                        .HasColumnName("TK1");

                    b.Property<int>("Tk10")
                        .HasColumnType("int")
                        .HasColumnName("TK10");

                    b.Property<int>("Tk100")
                        .HasColumnType("int")
                        .HasColumnName("TK100");

                    b.Property<int>("Tk1000")
                        .HasColumnType("int")
                        .HasColumnName("TK1000");

                    b.Property<int>("Tk2")
                        .HasColumnType("int")
                        .HasColumnName("TK2");

                    b.Property<int>("Tk20")
                        .HasColumnType("int")
                        .HasColumnName("TK20");

                    b.Property<int>("Tk5")
                        .HasColumnType("int")
                        .HasColumnName("TK5");

                    b.Property<int>("Tk50")
                        .HasColumnType("int")
                        .HasColumnName("TK50");

                    b.Property<int>("Tk500")
                        .HasColumnType("int")
                        .HasColumnName("TK500");

                    b.Property<decimal>("TotalAddition")
                        .HasColumnType("money");

                    b.Property<decimal?>("TotalDeduct")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDeductBank")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDeductCash")
                        .HasColumnType("money");

                    b.Property<float>("TotalOffDay")
                        .HasColumnType("real");

                    b.Property<string>("TotalOt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TotalOT");

                    b.Property<string>("TotalOtb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TotalOTB");

                    b.Property<decimal?>("TotalPayable")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("money");

                    b.Property<float>("TotalWorkDay")
                        .HasColumnType("real");

                    b.Property<decimal>("TotaldeductB")
                        .HasColumnType("money")
                        .HasColumnName("totaldeductB");

                    b.Property<decimal>("TotalpayableB")
                        .HasColumnType("money")
                        .HasColumnName("totalpayableB");

                    b.Property<decimal>("Transportcharge")
                        .HasColumnType("money");

                    b.Property<decimal>("Trn")
                        .HasColumnType("money");

                    b.Property<double?>("Trnd")
                        .HasColumnType("float")
                        .HasColumnName("trnd");

                    b.Property<short?>("TtlAbsent")
                        .HasColumnType("smallint");

                    b.Property<decimal>("UniFormAdd")
                        .HasColumnType("money");

                    b.Property<decimal>("UniFormDed")
                        .HasColumnType("money");

                    b.Property<decimal>("UnionSubDed")
                        .HasColumnType("money");

                    b.Property<string>("UnitName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("VigilanceDutyAllow")
                        .HasColumnType("money");

                    b.Property<Guid>("WId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wId");

                    b.Property<decimal>("WagesaAdv")
                        .HasColumnType("money");

                    b.Property<decimal>("WagesaAdvBal")
                        .HasColumnType("money");

                    b.Property<decimal>("WashingAllow")
                        .HasColumnType("money");

                    b.Property<decimal>("WashingAllowDed")
                        .HasColumnType("money");

                    b.Property<decimal>("WaterChargeOther")
                        .HasColumnType("money");

                    b.Property<decimal>("WaterExpRefund")
                        .HasColumnType("money");

                    b.Property<decimal>("Watercharge")
                        .HasColumnType("money");

                    b.Property<float>("Wday")
                        .HasColumnType("real");

                    b.Property<float>("WdayP")
                        .HasColumnType("real")
                        .HasColumnName("WDayP");

                    b.Property<int>("WelfareLid")
                        .HasColumnType("int")
                        .HasColumnName("WelfareLId");

                    b.Property<decimal>("Wfl")
                        .HasColumnType("money")
                        .HasColumnName("WFL");

                    b.Property<decimal>("WflloanBalance")
                        .HasColumnType("money")
                        .HasColumnName("WFLLoanBalance");

                    b.Property<decimal>("WfloanLocal")
                        .HasColumnType("money");

                    b.Property<decimal>("WfloanOther")
                        .HasColumnType("money");

                    b.Property<decimal>("WfloanOtherBal")
                        .HasColumnType("money");

                    b.Property<decimal>("Wfsub")
                        .HasColumnType("money");

                    b.Property<float>("WhdayAbsent")
                        .HasColumnType("real")
                        .HasColumnName("WHDayAbsent");

                    b.Property<decimal>("WhdayOtamt")
                        .HasColumnType("smallmoney")
                        .HasColumnName("WHDayOTAmt");

                    b.Property<float>("WhdayOthr")
                        .HasColumnType("real")
                        .HasColumnName("WHDayOTHr");

                    b.Property<float>("WhdayP")
                        .HasColumnType("real")
                        .HasColumnName("WHDayP");

                    b.Property<float>("WorkingDays")
                        .HasColumnType("real");

                    b.Property<decimal>("WpfloanDed")
                        .HasColumnType("money");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Suid");

                    b.ToTable("HR_ProcessedDataSalUpdate");
                });
#pragma warning restore 612, 618
        }
    }
}
