using System;
using System.Collections.Generic;

namespace GTERP_DAP_Model.CustomModels
{
    public partial class TblEmpRecruit
    {
        public long AEmpId { get; set; }
        public long EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpBname { get; set; }
        public string CurrAdd { get; set; }
        public string CurrCity { get; set; }
        public string CurrDist { get; set; }
        public string CurrZip { get; set; }
        public string PurAdd { get; set; }
        public string PurCity { get; set; }
        public string PurDist { get; set; }
        public string PurZip { get; set; }
        public string VEmpPh { get; set; }
        public string VEmpMobile { get; set; }
        public string VEmpCurrentRegion { get; set; }
        public string VEmpEmail { get; set; }
        public string VEmpPicLocation { get; set; }
        public string VEmpRemarks { get; set; }
        public string VEmpPrintAs { get; set; }
        public string VEmpFatherName { get; set; }
        public string VEmpMotherName { get; set; }
        public string VEmpSpouseName { get; set; }
        public string VEmpBloodgroup { get; set; }
        public string VEmpSex { get; set; }
        public DateTime? SdEmpBirthDate { get; set; }
        public string VEmpMaritalStatus { get; set; }
        public string VEmpReligion { get; set; }
        public string VEmpCaste { get; set; }
        public string VEmpPassportNo { get; set; }
        public string DesigId { get; set; }
        public string VEmpDesig { get; set; }
        public decimal? Bs { get; set; }
        public decimal? Ts { get; set; }
        public decimal? Prdbn { get; set; }
        public decimal? Trn { get; set; }
        public DateTime? SdEmpJoinDate { get; set; }
        public DateTime? SdlReleasedDate { get; set; }
        public string VEmpSkill { get; set; }
        public string SdEmpType { get; set; }
        public DateTime? SdEmpProvsionEndDate { get; set; }
        public string CompId { get; set; }
        public string VEmpOrg { get; set; }
        public string VEmpUnit { get; set; }
        public string VEmpDepartment { get; set; }
        public string SectId { get; set; }
        public string VEmpSec { get; set; }
        public string VEmpLine { get; set; }
        public string ShiftCode { get; set; }
        public string VEmpEducationLabel { get; set; }
        public string VEmpEducationMajor { get; set; }
        public string VEmpEducationYear { get; set; }
        public string VEmpGradeId { get; set; }
        public string VEmpGrade { get; set; }
        public string VEmpTestId { get; set; }
        public Guid? WEmpTest { get; set; }
        public string VEmpRefId { get; set; }
        public string WEmpRefId { get; set; }
        public string VEmpActiveYesNo { get; set; }
        public Guid? WEmpId { get; set; }
        public string CardId { get; set; }
        public string Ot { get; set; }
        public DateTime? QuitDate { get; set; }
        public string EmpSts { get; set; }
        public string Mn { get; set; }
        public string So { get; set; }
        public string WorkPlace { get; set; }
        public string GotPf { get; set; }
        public string Gotatt { get; set; }
        public string GotHoliBns { get; set; }
        public string GotGp { get; set; }
        public string Paymode { get; set; }
        public string Paysorce { get; set; }
        public decimal? Gp { get; set; }
        public string PloicyNo { get; set; }
        public decimal? Pp { get; set; }
        public string Sac { get; set; }
        public string CompName { get; set; }
        public string CompBang { get; set; }
        public int? Gs { get; set; }
        public DateTime? Confdate { get; set; }
        public string Vemptype { get; set; }
        public string Vref { get; set; }
        public string VAttnBns { get; set; }
        public string VEmpPlant { get; set; }
        public string VcancelCardNao { get; set; }
        public string VPf { get; set; }
        public string VOthAllow { get; set; }
        public string NightAllow { get; set; }
        public decimal? Attbns { get; set; }
        public decimal? OthAllow { get; set; }
        public string VEmpPurPo { get; set; }
        public string VEmpPurPs { get; set; }
        public DateTime? Pfdate { get; set; }
        public string Line { get; set; }
        public string SubLine { get; set; }
        public string Floore { get; set; }
        public int? AId { get; set; }
        public Guid WId { get; set; }
        public string CurrLocation { get; set; }
        public string MaritalStatus { get; set; }
        public string HomePhone { get; set; }
        public string Nationality { get; set; }
        public string OfficePhone { get; set; }
    }
}
