using System;
using System.Collections.Generic;

namespace GTERP_DAP_Model.CustomModels
{
    public partial class TblTempJobMonthly
    {
        public byte ComId { get; set; }
        public string ComName { get; set; }
        public string ComAdd1 { get; set; }
        public string ComAdd2 { get; set; }
        public string Caption { get; set; }
        public long EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public short? DesigId { get; set; }
        public string DesigName { get; set; }
        public string Grade { get; set; }
        public decimal? Gs { get; set; }
        public short? SectId { get; set; }
        public string SectName { get; set; }
        public string Floor { get; set; }
        public string Line { get; set; }
        public string DtJoin { get; set; }
        public string DtReleased { get; set; }
        public string D1in { get; set; }
        public string D1out { get; set; }
        public string D1ot { get; set; }
        public string D1sts { get; set; }
        public float D1otmin { get; set; }
        public string D2in { get; set; }
        public string D2out { get; set; }
        public string D2ot { get; set; }
        public string D2sts { get; set; }
        public float D2otmin { get; set; }
        public string D3in { get; set; }
        public string D3out { get; set; }
        public string D3ot { get; set; }
        public string D3sts { get; set; }
        public float D3otmin { get; set; }
        public string D4in { get; set; }
        public string D4out { get; set; }
        public string D4ot { get; set; }
        public string D4sts { get; set; }
        public float D4otmin { get; set; }
        public string D5in { get; set; }
        public string D5out { get; set; }
        public string D5ot { get; set; }
        public string D5sts { get; set; }
        public float D5otmin { get; set; }
        public string D6in { get; set; }
        public string D6out { get; set; }
        public string D6ot { get; set; }
        public string D6sts { get; set; }
        public float D6otmin { get; set; }
        public string D7in { get; set; }
        public string D7out { get; set; }
        public string D7ot { get; set; }
        public string D7sts { get; set; }
        public float D7otmin { get; set; }
        public string D8in { get; set; }
        public string D8out { get; set; }
        public string D8ot { get; set; }
        public string D8sts { get; set; }
        public float D8otmin { get; set; }
        public string D9in { get; set; }
        public string D9out { get; set; }
        public string D9ot { get; set; }
        public string D9sts { get; set; }
        public float D9otmin { get; set; }
        public string D10in { get; set; }
        public string D10out { get; set; }
        public string D10ot { get; set; }
        public string D10sts { get; set; }
        public float D10otmin { get; set; }
        public string D11in { get; set; }
        public string D11out { get; set; }
        public string D11ot { get; set; }
        public string D11sts { get; set; }
        public float D11otmin { get; set; }
        public string D12in { get; set; }
        public string D12out { get; set; }
        public string D12ot { get; set; }
        public string D12sts { get; set; }
        public float D12otmin { get; set; }
        public string D13in { get; set; }
        public string D13out { get; set; }
        public string D13ot { get; set; }
        public string D13sts { get; set; }
        public float D13otmin { get; set; }
        public string D14in { get; set; }
        public string D14out { get; set; }
        public string D14ot { get; set; }
        public string D14sts { get; set; }
        public float D14otmin { get; set; }
        public string D15in { get; set; }
        public string D15out { get; set; }
        public string D15ot { get; set; }
        public string D15sts { get; set; }
        public float D15otmin { get; set; }
        public string D16in { get; set; }
        public string D16out { get; set; }
        public string D16ot { get; set; }
        public string D16sts { get; set; }
        public float D16otmin { get; set; }
        public string D17in { get; set; }
        public string D17out { get; set; }
        public string D17ot { get; set; }
        public string D17sts { get; set; }
        public float D17otmin { get; set; }
        public string D18in { get; set; }
        public string D18out { get; set; }
        public string D18ot { get; set; }
        public string D18sts { get; set; }
        public float D18otmin { get; set; }
        public string D19in { get; set; }
        public string D19out { get; set; }
        public string D19ot { get; set; }
        public string D19sts { get; set; }
        public float D19otmin { get; set; }
        public string D20in { get; set; }
        public string D20out { get; set; }
        public string D20ot { get; set; }
        public string D20sts { get; set; }
        public float D20otmin { get; set; }
        public string D21in { get; set; }
        public string D21out { get; set; }
        public string D21ot { get; set; }
        public string D21sts { get; set; }
        public float D21otmin { get; set; }
        public string D22in { get; set; }
        public string D22out { get; set; }
        public string D22ot { get; set; }
        public string D22sts { get; set; }
        public float D22otmin { get; set; }
        public string D23in { get; set; }
        public string D23out { get; set; }
        public string D23ot { get; set; }
        public string D23sts { get; set; }
        public float D23otmin { get; set; }
        public string D24in { get; set; }
        public string D24out { get; set; }
        public string D24ot { get; set; }
        public string D24sts { get; set; }
        public float D24otmin { get; set; }
        public string D25in { get; set; }
        public string D25out { get; set; }
        public string D25ot { get; set; }
        public string D25sts { get; set; }
        public float D25otmin { get; set; }
        public string D26in { get; set; }
        public string D26out { get; set; }
        public string D26ot { get; set; }
        public string D26sts { get; set; }
        public float D26otmin { get; set; }
        public string D27in { get; set; }
        public string D27out { get; set; }
        public string D27ot { get; set; }
        public string D27sts { get; set; }
        public float D27otmin { get; set; }
        public string D28in { get; set; }
        public string D28out { get; set; }
        public string D28ot { get; set; }
        public string D28sts { get; set; }
        public float D28otmin { get; set; }
        public string D29in { get; set; }
        public string D29out { get; set; }
        public string D29ot { get; set; }
        public string D29sts { get; set; }
        public float D29otmin { get; set; }
        public string D30in { get; set; }
        public string D30out { get; set; }
        public string D30ot { get; set; }
        public string D30sts { get; set; }
        public float D30otmin { get; set; }
        public string D31in { get; set; }
        public string D31out { get; set; }
        public string D31ot { get; set; }
        public string D31sts { get; set; }
        public float D31otmin { get; set; }
        public long TotalOtmin { get; set; }
        public double TotalOthour { get; set; }
    }
}
